# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['server_standalone.py'],
    pathex=[],
    binaries=[
        ('print_tools/PDFtoPrinter_m.exe', 'print_tools'),
        ('print_tools/SumatraPDF-3.4.6-64.exe', 'print_tools'),
    ],
    datas=[
        ('static', 'static'),
        ('server/static', 'server/static'),
        ('web', 'web'),
        ('config.yaml', '.'),
        ('server/printer_config.yaml', 'server'),
        ('print_tools/SumatraPDF-settings.txt', 'print_tools'),
        ('print_tools/download_pdftoprinter.bat', 'print_tools'),
        ('README.md', '.'),
        ('INSTALL.md', '.'),
        ('USER_GUIDE.md', '.'),
    ],
    hiddenimports=[
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.loops.uvloop',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'fastapi.exceptions',
        'win32print',
        'win32api',
        'win32con',
        'win32gui',
        'win32file',
        'win32security',
        'pywintypes',
        'yaml',
        'PIL',
        'PIL._tkinter_finder',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'zeroconf',
        'zeroconf._utils.ipaddress',
        'zeroconf._handlers.answers',
        'multipart',
        'multipart.multipart',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.responses',
        'starlette.staticfiles',
        'starlette.exceptions',
        'pydantic',
        'pydantic.main',
        'pydantic.fields',
        'pydantic.types',
        'loguru',
        'psutil',
        'requests',
        'json',
        'pathlib',
        'threading',
        'asyncio',
        'contextlib',
        'socket',
        'time',
        'os',
        'sys',
        'logging',
        'traceback',
        'PyPDF2',
        'fitz',  # PyMuPDF
        'reportlab',
        'openpyxl',
        'docx',
        'docx2pdf',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'numpy',
        'scipy',
        'tkinter',
        'test',
        'tests',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PrinterServer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)